[package]
name = "email_forwarder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
imap = { version = "3.0.0-alpha.10" }
lettre = "0.10.4"
# rustls = "0.21.3"
native-tls = "0.2.11"
serde = { version = "1.0.170", features = ["derive"] }
toml = "0.7.6"
